logging:
  level:
    com.codedifferently.studycrm: DEBUG 
    org.springframework.security: DEBUG
    io.eventuate: DEBUG

spring:
  config:
    activate.on-profile: production
  datasource:
      url: jdbc:mysql://${DOCKER_HOST_IP:localhost}:3309/auth_service
      username: mysqluser
      password: mysqlpw
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
          initialization-fail-timeout: 30000
  sleuth:
      enabled: true
      sampler:
          probability: 1
  zipkin:
      base-url: http://${DOCKER_HOST_IP:localhost}:9411/
  flyway:
      locations: classpath:flyway/{vendor}
      baseline-on-migrate: true
      baseline-version: 0
  
eventuatelocal:
  kafka:
    bootstrap:
      servers: ${DOCKER_HOST_IP:localhost}:9092
  zookeeper:
    connection:
      string: ${DOCKER_HOST_IP:localhost}:2181