server:
  port: 8081

logging:
  level:
    com.codedifferently.studycrm: TRACE 
    org.springframework.security: TRACE

spring:
  application:
      name: auth-service
  jpa:
      generate-ddl: true
  datasource:
      url: jdbc:mysql://${DOCKER_HOST_IP:localhost}:3309/auth_service
      username: mysqluser
      password: mysqlpw
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
          initialization-fail-timeout: 30000
  sleuth:
      enabled: true
      sampler:
          probability: 1
  zipkin:
      base-url: http://${DOCKER_HOST_IP:localhost}:9411/
  flyway:
      locations: classpath:flyway/{vendor}
      baseline-on-migrate: true
      baseline-version: 0
  cache:
      jcache:
          config: classpath:ehcache.xml
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
        provider:
          google:
            user-name-attribute: email
  
eventuatelocal:
  kafka:
    bootstrap:
      servers: ${DOCKER_HOST_IP:localhost}:9092
  zookeeper:
    connection:
      string: ${DOCKER_HOST_IP:localhost}:2181