server:
    port: 8082
spring:
    profiles:
        default: production
    application:
        name: organization-service
    jpa:
        generate-ddl: true
    flyway:
        locations: classpath:flyway/{vendor}
        baseline-on-migrate: true
        baseline-version: 0  
    cache:
        jcache:
            config: classpath:ehcache.xml
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://api-local.studycrm.com